# file: C:\Users\micha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\coverage\control.py
# hypothesis_version: 6.138.15

[' (disabled)', ', ', '-none-', ':data:', 'COVERAGE_DEBUG_CALLS', 'CTracer', 'Coverage._init', 'MISSING', '_is_gil_enabled', 'argv', 'atexit', 'build', 'command_line', 'config', 'config_contents', 'config_file', 'configs_attempted', 'configs_read', 'core', 'coverage', 'coverage_module', 'coverage_version', 'cwd', 'data_file', 'def_encoding', 'dynamic-conflict', 'end', 'environment', 'exclude', 'executable', 'fs_encoding', 'get_data', 'gil_enabled', 'implementation', 'multiprocessing', 'no-data-collected', 'none', 'path', 'pathmap', 'pid', 'platform', 'plugins.configurers', 'plugins.file_tracers', 'process', 'pybehave', 'python', 'sigterm', 'sys', 'sys: ', 'test_function', 'trace', 'unavailable']